version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Torc@123"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "Torc@123"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
