version: '3.8'

services:
  mydb:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'torclibrary'
      MYSQL_ROOT_PASSWORD: "Torc@123"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "Torc@123"
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
  web_api:
    build: .
    container_name: torclibrary
    ports:
      - "5000:80"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 2s
      retries: 10

volumes:
  mysql_data:
