// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torc.BookLibrary.Data;

#nullable disable

namespace Torc.BookLibrary.Data.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20240409070828_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Torc.BookLibrary.Data.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CopiesInUse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TotalCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("BookId");

                    b.HasIndex("Category");

                    b.HasIndex("FirstName");

                    b.HasIndex("ISBN");

                    b.HasIndex("LastName");

                    b.HasIndex("Title");

                    b.HasIndex("Type");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Category = "Fiction",
                            CopiesInUse = 80,
                            FirstName = "Jane",
                            ISBN = "1234567891",
                            LastName = "Austen",
                            Title = "Pride and Prejudice",
                            TotalCopies = 100,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 2,
                            Category = "Fiction",
                            CopiesInUse = 65,
                            FirstName = "Harper",
                            ISBN = "1234567892",
                            LastName = "Lee",
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 75,
                            Type = "Paperback"
                        },
                        new
                        {
                            BookId = 3,
                            Category = "Fiction",
                            CopiesInUse = 45,
                            FirstName = "J.D.",
                            ISBN = "1234567893",
                            LastName = "Salinger",
                            Title = "The Catcher in the Rye",
                            TotalCopies = 50,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 4,
                            Category = "Non-Fiction",
                            CopiesInUse = 22,
                            FirstName = "F. Scott",
                            ISBN = "1234567894",
                            LastName = "Fitzgerald",
                            Title = "The Great Gatsby",
                            TotalCopies = 50,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 5,
                            Category = "Biography",
                            CopiesInUse = 35,
                            FirstName = "Paulo",
                            ISBN = "1234567895",
                            LastName = "Coelho",
                            Title = "The Alchemist",
                            TotalCopies = 50,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 6,
                            Category = "Mystery",
                            CopiesInUse = 11,
                            FirstName = "Markus",
                            ISBN = "1234567896",
                            LastName = "Zusak",
                            Title = "The Book Thief",
                            TotalCopies = 75,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 7,
                            Category = "Sci-Fi",
                            CopiesInUse = 14,
                            FirstName = "C.S.",
                            ISBN = "1234567897",
                            LastName = "Lewis",
                            Title = "The Chronicles of Narnia",
                            TotalCopies = 100,
                            Type = "Paperback"
                        },
                        new
                        {
                            BookId = 8,
                            Category = "Sci-Fi",
                            CopiesInUse = 40,
                            FirstName = "Dan",
                            ISBN = "1234567898",
                            LastName = "Brown",
                            Title = "The Da Vinci Code",
                            TotalCopies = 50,
                            Type = "Paperback"
                        },
                        new
                        {
                            BookId = 9,
                            Category = "Fiction",
                            CopiesInUse = 35,
                            FirstName = "John",
                            ISBN = "1234567899",
                            LastName = "Steinbeck",
                            Title = "The Grapes of Wrath",
                            TotalCopies = 50,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 10,
                            Category = "Non-Fiction",
                            CopiesInUse = 35,
                            FirstName = "Douglas",
                            ISBN = "1234567900",
                            LastName = "Adams",
                            Title = "The Hitchhiker's Guide to the Galaxy",
                            TotalCopies = 50,
                            Type = "Paperback"
                        },
                        new
                        {
                            BookId = 11,
                            Category = "Fiction",
                            CopiesInUse = 8,
                            FirstName = "Herman",
                            ISBN = "8901234567",
                            LastName = "Melville",
                            Title = "Moby-Dick",
                            TotalCopies = 30,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 12,
                            Category = "Non-Fiction",
                            CopiesInUse = 0,
                            FirstName = "Harper",
                            ISBN = "9012345678",
                            LastName = "Lee",
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 20,
                            Type = "Paperback"
                        },
                        new
                        {
                            BookId = 13,
                            Category = "Non-Fiction",
                            CopiesInUse = 1,
                            FirstName = "J.D.",
                            ISBN = "0123456789",
                            LastName = "Salinger",
                            Title = "The Catcher in the Rye",
                            TotalCopies = 10,
                            Type = "Hardcover"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
